openapi: 3.1.0
info:
  title: Chrono AST Gate
  version: "2.0.0"
servers:
  - url: https://YOUR-RENDER-URL
paths:
  /validate:
    post:
      operationId: validate_code
      summary: Validate Python code against PyChrono 9.0.1-only AST rules (chrono/veh/irr/fea)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
      responses:
        "200":
          description: Result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  errors:
                    type: array
                    items: { type: string }
